// ZygorGuidesViewer.lua -- pt-BR for the "Profiles" options tab, which is generated by the AceDBOptions-3.0 library
// (English only; and whichever copy of the library wins in LibStub may belong to another addon, so we translate the
//  generated table at runtime instead of editing the embedded library).
const PT = {
  "You can change the active database profile, so you can have different settings for every character.":
    "Você pode alterar o perfil ativo do banco de dados, para ter configurações diferentes para cada personagem.",
  "Reset the current profile back to its default values, in case your configuration is broken, or you simply want to start over.":
    "Redefine o perfil atual para os valores padrão, caso sua configuração esteja quebrada ou você simplesmente queira começar do zero.",
  "Reset Profile": "Redefinir Perfil",
  "Reset the current profile to the default": "Redefine o perfil atual para o padrão",
  "You can either create a new profile by entering a name in the editbox, or choose one of the already existing profiles.":
    "Você pode criar um novo perfil digitando um nome na caixa de texto ou escolher um dos perfis já existentes.",
  "New": "Novo",
  "Create a new empty profile.": "Cria um novo perfil vazio.",
  "Existing Profiles": "Perfis Existentes",
  "Select one of your currently available profiles.": "Selecione um dos perfis atualmente disponíveis.",
  "Copy the settings from one existing profile into the currently active profile.":
    "Copia as configurações de um perfil existente para o perfil ativo.",
  "Copy From": "Copiar de",
  "Delete existing and unused profiles from the database to save space, and cleanup the SavedVariables file.":
    "Exclui do banco de dados perfis existentes e não utilizados para economizar espaço e limpar o arquivo SavedVariables.",
  "Delete a Profile": "Excluir um Perfil",
  "Deletes a profile from the database.": "Exclui um perfil do banco de dados.",
  "Are you sure you want to delete the selected profile?": "Tem certeza de que deseja excluir o perfil selecionado?",
  "Profiles": "Perfis",
  "Manage Profiles": "Gerenciar Perfis",
};
const luaStr = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
const entries = Object.entries(PT).map(([k, v]) => '\t\t\t[' + luaStr(k) + '] = ' + luaStr(v) + ',\n').join('');

module.exports = [
  {
    find: 'self.optionsprofile = LibStub("AceDBOptions-3.0"):GetOptionsTable(self.db)\n',
    replace:
      'self.optionsprofile = LibStub("AceDBOptions-3.0"):GetOptionsTable(self.db)\n' +
      '\n' +
      '\t-- pt-BR: the Profiles tab comes from the AceDBOptions library (English only); translate the generated table (Portuguese mode only)\n' +
      '\tif ZGV_LANG_PT then\n' +
      '\t\tlocal PT = {\n' + entries + '\t\t}\n' +
      '\t\tlocal function tr(s)\n' +
      '\t\t\tlocal pre, core, post = s:match("^(\\n*)(.-)(\\n*)$")\n' +
      '\t\t\treturn (core and PT[core]) and (pre .. PT[core] .. post) or s\n' +
      '\t\tend\n' +
      '\t\tlocal seen = {}\n' +
      '\t\tlocal function walk(t)\n' +
      '\t\t\tif type(t) ~= "table" or seen[t] then return end\n' +
      '\t\t\tseen[t] = true\n' +
      '\t\t\tfor _, key in ipairs({"name", "desc", "confirmText"}) do\n' +
      '\t\t\t\tlocal v = t[key]\n' +
      '\t\t\t\tif type(v) == "string" then\n' +
      '\t\t\t\t\tt[key] = tr(v)\n' +
      '\t\t\t\telseif type(v) == "function" and key == "name" then\n' +
      '\t\t\t\t\tt[key] = function(...)\n' +
      '\t\t\t\t\t\tlocal r = v(...)\n' +
      '\t\t\t\t\t\tif type(r) == "string" then r = (r:gsub("^Current Profile:", "Perfil atual:")) end\n' +
      '\t\t\t\t\t\treturn r\n' +
      '\t\t\t\t\tend\n' +
      '\t\t\t\tend\n' +
      '\t\t\tend\n' +
      '\t\t\tif type(t.args) == "table" then\n' +
      '\t\t\t\tfor _, sub in pairs(t.args) do walk(sub) end\n' +
      '\t\t\tend\n' +
      '\t\tend\n' +
      '\t\twalk(self.optionsprofile)\n' +
      '\tend\n',
  },
];
